
server:
  port: 10010
spring:
  application:
    name: leyou-gateway
  main:
    allow-bean-definition-overriding: true     # 当遇到同样名字，是否允许覆盖注册
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    regsitry-fetch-interval-second: 5
zuul:
  prefix: /api
  routes:
    item-service: /item/**        # 路由到商品的微服务

